### ISSUE TITLE
[Feature] Create action for checking out build and deploy preview for everyone

### ISSUE THREAD

**Issue by avats-dev** [shivamsouravjha/Meme_Yogi#9]
#### Not everyone would like to check out the project by forking and cloning and then running it on their local machine as it takes time . So, to get better and faster pipeline for feedbacks and testing, you can follow these options:

- Deploy this somewhere for free, like on heroku and add the link of the same in readme and description to make it easily accessible.
- You can also use gitpod for the same for free and it also provides on cloud dev environment to tweak changes. 
- You can also use netlify as an alternative to heroku.
- Make a build action for the project to test out the crashes, bugs and linting errors. You can find existing actions for such based on your codebase from github marketplace.
- This will also help you in deploying it after you're good to release it in future.

---

### References
- [For using Github Heroku integration](https://devcenter.heroku.com/articles/github-integration)
- [For using Heroku with Node.js](https://devcenter.heroku.com/categories/nodejs-support)
- [For using Heroku with Git](https://devcenter.heroku.com/articles/git)
- [Gitpod GitHub Integration Docs](https://www.gitpod.io/docs/github-integration/)
- [Netlify Development Docs](https://docs.netlify.com/configure-builds/get-started/)

*Cannot help you, not proficient with `js`.* 
Great, Keep going. 👍

**Comment by shivamsouravjha** [comment]
Deployed on heroku postman links in description
